import{z}from"zod";import{CommandSchema,type Command}from"../../command-schema/src/index.js";import type{FurnitureProjectState}from"../../project-state/src/schema.js";import{getPrompt,PROMPT_VERSION,type PromptDefinition}from"./prompt.js";export*from"./prompt.js";export*from"./conversation.js";
export type CompactProjectSummary={wallWidth:number|null;roomHeight:number|null;moduleIds:string[];remainingWidth:number|null;stage:string};
export type ProviderRequest={utterance:string;locale:"ru-KZ"|"kk-KZ";projectSummary:CompactProjectSummary;prompt:PromptDefinition};export type ProviderUsage={inputTokens:number;cachedInputTokens?:number;outputTokens:number};export type ProviderResponse={output:unknown;usage:ProviderUsage};
export interface IntentProvider{complete(request:ProviderRequest):Promise<ProviderResponse>}
export class FakeIntentProvider implements IntentProvider{readonly requests:ProviderRequest[]=[];constructor(private readonly responses:ProviderResponse[]){}async complete(request:ProviderRequest){this.requests.push(structuredClone(request));const response=this.responses.shift();if(!response)throw new Error("Fake provider has no response.");return structuredClone(response)}}
export const ClarifySchema=z.object({type:z.literal("CLARIFY"),question:z.string().min(1).max(240),options:z.array(z.string().min(1)).max(3).optional(),confidence:z.number().min(0).max(1).default(0)});
const CommandIntentEnvelopeSchema=z.object({confidence:z.number().min(0).max(1),explanation:z.string().min(1).max(240).optional()}).passthrough();
const ProviderUsageSchema=z.object({inputTokens:z.number().int().nonnegative(),cachedInputTokens:z.number().int().nonnegative().optional(),outputTokens:z.number().int().nonnegative()});
export type IntentResult={kind:"command";command:Command;confidence:number;needsConfirmation:boolean;explanation:string;usage:ProviderUsage}|{kind:"clarify";question:string;options?:string[];confidence:number;usage:ProviderUsage}|{kind:"rejected";reason:string;usage:ProviderUsage};
export function compactProjectState(state:FurnitureProjectState):CompactProjectSummary{const occupied=state.lowerRow.modules.reduce((sum,module)=>sum+module.width,0);return{wallWidth:state.room.wallWidth,roomHeight:state.room.roomHeight,moduleIds:state.lowerRow.modules.map(module=>module.id),remainingWidth:state.room.wallWidth===null?null:state.room.wallWidth-occupied,stage:state.stage}}
export async function parseIntent(provider:IntentProvider,utterance:string,state:FurnitureProjectState,locale:"ru-KZ"|"kk-KZ"="ru-KZ"):Promise<IntentResult>{const clean=utterance.trim();if(!clean)return{kind:"rejected",reason:"Введите команду текстом.",usage:{inputTokens:0,outputTokens:0}};let raw:ProviderResponse;try{raw=await provider.complete({utterance:clean,locale,projectSummary:compactProjectState(state),prompt:getPrompt(PROMPT_VERSION)})}catch{return{kind:"rejected",reason:"Не удалось распознать команду. Схема не изменена.",usage:{inputTokens:0,outputTokens:0}}}const usage=ProviderUsageSchema.safeParse(raw.usage);if(!usage.success)return{kind:"rejected",reason:"Провайдер вернул некорректные данные использования. Схема не изменена.",usage:{inputTokens:0,outputTokens:0}};const clarify=ClarifySchema.safeParse(raw.output);if(clarify.success)return{kind:"clarify",question:clarify.data.question,options:clarify.data.options,confidence:clarify.data.confidence,usage:usage.data};const envelope=CommandIntentEnvelopeSchema.safeParse(raw.output);if(!envelope.success)return{kind:"rejected",reason:"Ответ AI не соответствует безопасному контракту. Схема не изменена.",usage:usage.data};const rawObject=envelope.data as Record<string,unknown>;const candidate=rawObject.command??Object.fromEntries(Object.entries(rawObject).filter(([key])=>!["confidence","explanation","needsConfirmation"].includes(key)));const command=CommandSchema.safeParse(candidate);if(!command.success)return{kind:"rejected",reason:"AI предложил неизвестную или некорректную команду. Схема не изменена.",usage:usage.data};return{kind:"command",command:command.data,confidence:envelope.data.confidence,needsConfirmation:envelope.data.confidence<.9,explanation:envelope.data.explanation??`Применить команду ${command.data.type}`,usage:usage.data}}
