import { CommandSchema,type Command } from "../../command-schema/src/index.js";
import { createModule,isAllowedModuleWidth } from "../../project-state/src/catalog.js";
import { FurnitureProjectStateSchema,type FurnitureModule,type FurnitureProjectState } from "../../project-state/src/schema.js";
import type { ProjectHistory } from "../../project-state/src/reducer.js";
export class LayoutError extends Error{} export type LayoutWarning={code:string;message:string};export type LayoutResult={state:FurnitureProjectState;remainingWidth:number|null;warnings:LayoutWarning[]};type LayoutCommand=Exclude<Command,{type:"UNDO"|"REDO"}>;const UPPER_HEIGHTS=[900,800,720]as const;
function normalizePositions(modules:FurnitureModule[]){let position=0;return modules.map(module=>{const next={...module,position};position+=module.width;return next})}
export function calculateRemainingWidth(state:FurnitureProjectState){if(state.room.wallWidth===null)return null;return state.room.wallWidth-state.lowerRow.modules.reduce((sum,module)=>sum+module.width,0)}
export function calculateAvailableUpperHeight(state:FurnitureProjectState){if(state.room.roomHeight===null)return null;return state.room.roomHeight-state.lowerRow.totalHeight-state.upperRow.apronHeight-state.room.ceilingGap}
function validateModulePlacement(modules:FurnitureModule[],module:FurnitureModule,index:number){if(!isAllowedModuleWidth(module.type,module.width))throw new LayoutError("Ширина не разрешена для этого типа модуля.");if(module.type==="filler"&&index!==0&&index!==modules.length)throw new LayoutError("Добор можно размещать только у края ряда.")}
function computeWarnings(state:FurnitureProjectState):LayoutWarning[]{const warnings:LayoutWarning[]=[];const remaining=calculateRemainingWidth(state);if(remaining!==null){if(remaining<0)throw new LayoutError(`Модули превышают ширину стены на ${Math.abs(remaining)} мм.`);if(remaining>0&&remaining<=50)warnings.push({code:"technology_gap",message:`Остался технологический зазор ${remaining} мм.`});else if(remaining<=149&&remaining>50)warnings.push({code:"filler_recommended",message:`Осталось ${remaining} мм. Рекомендуется добор.`});else if(remaining>=150)warnings.push({code:"module_space_available",message:`Осталось ${remaining} мм. Можно добавить модуль.`})}const modules=state.lowerRow.modules;for(let i=0;i<modules.length;i++){const module=modules[i];if(module?.type.startsWith("dishwasher")){const left=modules[i-1]?.type;const right=modules[i+1]?.type;if(left!=="sink_cabinet"&&right!=="sink_cabinet")warnings.push({code:"dishwasher_away_from_sink",message:"Посудомойка не находится рядом с мойкой. Проверьте подключение."})}}return warnings}
function validateUpper(state:FurnitureProjectState){if(!state.upperRow.enabled)return;const available=calculateAvailableUpperHeight(state);if(available===null)throw new LayoutError("Сначала укажите высоту помещения.");const used=state.upperRow.mainCabinetHeight+(state.upperRow.mezzanineHeight??0);if(used>available)throw new LayoutError(`Верхний ряд выше доступного пространства на ${used-available} мм.`)}
function validateRow(state:FurnitureProjectState){const modules=state.lowerRow.modules;modules.forEach((module,index)=>{if(!isAllowedModuleWidth(module.type,module.width))throw new LayoutError("Ширина не разрешена для этого типа модуля.");if(module.type==="filler"&&index!==0&&index!==modules.length-1)throw new LayoutError("Добор можно размещать только у края ряда.")})}
export function generateUpperRow(state:FurnitureProjectState,preferred?:720|800|900){const next=structuredClone(state);const available=calculateAvailableUpperHeight(next);if(available===null)throw new LayoutError("Сначала укажите высоту помещения.");const candidates:readonly(720|800|900)[]=preferred?[preferred,...UPPER_HEIGHTS.filter(h=>h!==preferred)]:UPPER_HEIGHTS;const main=candidates.find(height=>height<=available);if(!main)throw new LayoutError("Недостаточно места для стандартного верхнего ряда.");const remainder=available-main;next.upperRow.enabled=true;next.upperRow.mainCabinetHeight=main;next.upperRow.mezzanineHeight=remainder>=400?remainder:null;validateUpper(next);return next}
export function applyLayoutCommand(state:FurnitureProjectState,command:LayoutCommand):LayoutResult{const next=structuredClone(state);const modules=next.lowerRow.modules;switch(command.type){
case"SET_WALL_WIDTH":next.room.wallWidth=command.payload.width;break;case"SET_ROOM_HEIGHT":next.room.roomHeight=command.payload.height;break;
case"ADD_MODULE":{if(modules.some(m=>m.id===command.payload.id))throw new LayoutError("ID модуля уже существует.");const module=createModule(command.payload.id,command.payload.moduleType,command.payload.width);const index=command.payload.edge==="left"?0:modules.length;validateModulePlacement(modules,module,index);modules.splice(index,0,module);break}
case"REMOVE_MODULE":{const index=modules.findIndex(m=>m.id===command.payload.id);if(index<0)throw new LayoutError("Модуль не найден.");modules.splice(index,1);break}
case"INSERT_BEFORE":case"INSERT_AFTER":{const reference=modules.findIndex(m=>m.id===command.referenceId);if(reference<0)throw new LayoutError("Опорный модуль не найден.");if(modules.some(m=>m.id===command.payload.id))throw new LayoutError("ID модуля уже существует.");const module=createModule(command.payload.id,command.payload.moduleType,command.payload.width);const index=command.type==="INSERT_BEFORE"?reference:reference+1;validateModulePlacement(modules,module,index);modules.splice(index,0,module);break}
case"MOVE_TO_EDGE":{const index=modules.findIndex(m=>m.id===command.payload.id);if(index<0)throw new LayoutError("Модуль не найден.");const[module]=modules.splice(index,1);if(!module)throw new LayoutError("Модуль не найден.");modules.splice(command.payload.edge==="left"?0:modules.length,0,module);break}
case"MOVE_LEFT":case"MOVE_RIGHT":{const index=modules.findIndex(m=>m.id===command.payload.id);if(index<0)throw new LayoutError("Модуль не найден.");const target=command.type==="MOVE_LEFT"?index-1:index+1;if(target>=0&&target<modules.length)[modules[index],modules[target]]=[modules[target]!,modules[index]!];break}
case"CHANGE_WIDTH":{const module=modules.find(m=>m.id===command.payload.id);if(!module)throw new LayoutError("Модуль не найден.");if(!isAllowedModuleWidth(module.type,command.payload.width))throw new LayoutError("Ширина не разрешена для этого типа модуля.");module.width=command.payload.width;break}
case"SET_APRON_HEIGHT":next.upperRow.apronHeight=command.payload.height;break;case"GENERATE_UPPER_ROW":return finalize(generateUpperRow(next,command.payload.preferredMainHeight));case"SET_MEZZANINE_HEIGHT":next.upperRow.enabled=true;next.upperRow.mezzanineHeight=command.payload.height;break}
return finalize(next)}
function finalize(state:FurnitureProjectState):LayoutResult{state.lowerRow.modules=normalizePositions(state.lowerRow.modules);validateRow(state);validateUpper(state);const warnings=computeWarnings(state);state.warnings=warnings;const parsed=FurnitureProjectStateSchema.parse(state);return{state:parsed,remainingWidth:calculateRemainingWidth(parsed),warnings}}

export function applyLayoutCommandToHistory(history:ProjectHistory,input:unknown):ProjectHistory{const command=CommandSchema.parse(input);if(history.processedCommandIds.includes(command.commandId))return history;const processedCommandIds=[...history.processedCommandIds,command.commandId];if(command.type==="UNDO"){const previous=history.past.at(-1);if(!previous)return{...history,processedCommandIds};return{present:previous,past:history.past.slice(0,-1),future:[history.present,...history.future],processedCommandIds}}if(command.type==="REDO"){const next=history.future[0];if(!next)return{...history,processedCommandIds};return{present:next,past:[...history.past,history.present],future:history.future.slice(1),processedCommandIds}}const result=applyLayoutCommand(history.present,command);const present=structuredClone(result.state);present.historyMeta.revision=history.present.historyMeta.revision+1;present.historyMeta.appliedCommandIds=[...history.present.historyMeta.appliedCommandIds,command.commandId];const parsed=FurnitureProjectStateSchema.parse(present);return{present:parsed,past:[...history.past,history.present],future:[],processedCommandIds}}
